/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DesignRouteImport } from './routes/design'
import { Route as CtextRouteImport } from './routes/ctext'
import { Route as ClassimedRouteImport } from './routes/_classimed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClassimedTodoRouteImport } from './routes/_classimed/todo'
import { Route as ClassimedReaderRouteImport } from './routes/_classimed/reader'
import { Route as ClassimedLibraryRouteImport } from './routes/_classimed/library'
import { Route as ClassimedImportRouteImport } from './routes/_classimed/import'
import { Route as ClassimedGlossaryRouteImport } from './routes/_classimed/glossary'
import { Route as ClassimedConfigRouteImport } from './routes/_classimed/config'

const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const CtextRoute = CtextRouteImport.update({
  id: '/ctext',
  path: '/ctext',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassimedRoute = ClassimedRouteImport.update({
  id: '/_classimed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassimedTodoRoute = ClassimedTodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => ClassimedRoute,
} as any)
const ClassimedReaderRoute = ClassimedReaderRouteImport.update({
  id: '/reader',
  path: '/reader',
  getParentRoute: () => ClassimedRoute,
} as any)
const ClassimedLibraryRoute = ClassimedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => ClassimedRoute,
} as any)
const ClassimedImportRoute = ClassimedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => ClassimedRoute,
} as any)
const ClassimedGlossaryRoute = ClassimedGlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => ClassimedRoute,
} as any)
const ClassimedConfigRoute = ClassimedConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => ClassimedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ctext': typeof CtextRoute
  '/design': typeof DesignRoute
  '/config': typeof ClassimedConfigRoute
  '/glossary': typeof ClassimedGlossaryRoute
  '/import': typeof ClassimedImportRoute
  '/library': typeof ClassimedLibraryRoute
  '/reader': typeof ClassimedReaderRoute
  '/todo': typeof ClassimedTodoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ctext': typeof CtextRoute
  '/design': typeof DesignRoute
  '/config': typeof ClassimedConfigRoute
  '/glossary': typeof ClassimedGlossaryRoute
  '/import': typeof ClassimedImportRoute
  '/library': typeof ClassimedLibraryRoute
  '/reader': typeof ClassimedReaderRoute
  '/todo': typeof ClassimedTodoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_classimed': typeof ClassimedRouteWithChildren
  '/ctext': typeof CtextRoute
  '/design': typeof DesignRoute
  '/_classimed/config': typeof ClassimedConfigRoute
  '/_classimed/glossary': typeof ClassimedGlossaryRoute
  '/_classimed/import': typeof ClassimedImportRoute
  '/_classimed/library': typeof ClassimedLibraryRoute
  '/_classimed/reader': typeof ClassimedReaderRoute
  '/_classimed/todo': typeof ClassimedTodoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ctext'
    | '/design'
    | '/config'
    | '/glossary'
    | '/import'
    | '/library'
    | '/reader'
    | '/todo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ctext'
    | '/design'
    | '/config'
    | '/glossary'
    | '/import'
    | '/library'
    | '/reader'
    | '/todo'
  id:
    | '__root__'
    | '/'
    | '/_classimed'
    | '/ctext'
    | '/design'
    | '/_classimed/config'
    | '/_classimed/glossary'
    | '/_classimed/import'
    | '/_classimed/library'
    | '/_classimed/reader'
    | '/_classimed/todo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClassimedRoute: typeof ClassimedRouteWithChildren
  CtextRoute: typeof CtextRoute
  DesignRoute: typeof DesignRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ctext': {
      id: '/ctext'
      path: '/ctext'
      fullPath: '/ctext'
      preLoaderRoute: typeof CtextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_classimed': {
      id: '/_classimed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ClassimedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_classimed/todo': {
      id: '/_classimed/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof ClassimedTodoRouteImport
      parentRoute: typeof ClassimedRoute
    }
    '/_classimed/reader': {
      id: '/_classimed/reader'
      path: '/reader'
      fullPath: '/reader'
      preLoaderRoute: typeof ClassimedReaderRouteImport
      parentRoute: typeof ClassimedRoute
    }
    '/_classimed/library': {
      id: '/_classimed/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof ClassimedLibraryRouteImport
      parentRoute: typeof ClassimedRoute
    }
    '/_classimed/import': {
      id: '/_classimed/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ClassimedImportRouteImport
      parentRoute: typeof ClassimedRoute
    }
    '/_classimed/glossary': {
      id: '/_classimed/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof ClassimedGlossaryRouteImport
      parentRoute: typeof ClassimedRoute
    }
    '/_classimed/config': {
      id: '/_classimed/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ClassimedConfigRouteImport
      parentRoute: typeof ClassimedRoute
    }
  }
}

interface ClassimedRouteChildren {
  ClassimedConfigRoute: typeof ClassimedConfigRoute
  ClassimedGlossaryRoute: typeof ClassimedGlossaryRoute
  ClassimedImportRoute: typeof ClassimedImportRoute
  ClassimedLibraryRoute: typeof ClassimedLibraryRoute
  ClassimedReaderRoute: typeof ClassimedReaderRoute
  ClassimedTodoRoute: typeof ClassimedTodoRoute
}

const ClassimedRouteChildren: ClassimedRouteChildren = {
  ClassimedConfigRoute: ClassimedConfigRoute,
  ClassimedGlossaryRoute: ClassimedGlossaryRoute,
  ClassimedImportRoute: ClassimedImportRoute,
  ClassimedLibraryRoute: ClassimedLibraryRoute,
  ClassimedReaderRoute: ClassimedReaderRoute,
  ClassimedTodoRoute: ClassimedTodoRoute,
}

const ClassimedRouteWithChildren = ClassimedRoute._addFileChildren(
  ClassimedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClassimedRoute: ClassimedRouteWithChildren,
  CtextRoute: CtextRoute,
  DesignRoute: DesignRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
