/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DesignRouteImport } from './routes/design'
import { Route as ClassimedRouteImport } from './routes/_classimed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClassimedTodoRouteImport } from './routes/_classimed/todo'
import { Route as ClassimedReaderRouteImport } from './routes/_classimed/reader'
import { Route as ClassimedLibraryRouteImport } from './routes/_classimed/library'
import { Route as ClassimedGlossaryRouteImport } from './routes/_classimed/glossary'

const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassimedRoute = ClassimedRouteImport.update({
  id: '/_classimed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassimedTodoRoute = ClassimedTodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => ClassimedRoute,
} as any)
const ClassimedReaderRoute = ClassimedReaderRouteImport.update({
  id: '/reader',
  path: '/reader',
  getParentRoute: () => ClassimedRoute,
} as any)
const ClassimedLibraryRoute = ClassimedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => ClassimedRoute,
} as any)
const ClassimedGlossaryRoute = ClassimedGlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => ClassimedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/glossary': typeof ClassimedGlossaryRoute
  '/library': typeof ClassimedLibraryRoute
  '/reader': typeof ClassimedReaderRoute
  '/todo': typeof ClassimedTodoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/glossary': typeof ClassimedGlossaryRoute
  '/library': typeof ClassimedLibraryRoute
  '/reader': typeof ClassimedReaderRoute
  '/todo': typeof ClassimedTodoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_classimed': typeof ClassimedRouteWithChildren
  '/design': typeof DesignRoute
  '/_classimed/glossary': typeof ClassimedGlossaryRoute
  '/_classimed/library': typeof ClassimedLibraryRoute
  '/_classimed/reader': typeof ClassimedReaderRoute
  '/_classimed/todo': typeof ClassimedTodoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/design' | '/glossary' | '/library' | '/reader' | '/todo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/design' | '/glossary' | '/library' | '/reader' | '/todo'
  id:
    | '__root__'
    | '/'
    | '/_classimed'
    | '/design'
    | '/_classimed/glossary'
    | '/_classimed/library'
    | '/_classimed/reader'
    | '/_classimed/todo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClassimedRoute: typeof ClassimedRouteWithChildren
  DesignRoute: typeof DesignRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_classimed': {
      id: '/_classimed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ClassimedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_classimed/todo': {
      id: '/_classimed/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof ClassimedTodoRouteImport
      parentRoute: typeof ClassimedRoute
    }
    '/_classimed/reader': {
      id: '/_classimed/reader'
      path: '/reader'
      fullPath: '/reader'
      preLoaderRoute: typeof ClassimedReaderRouteImport
      parentRoute: typeof ClassimedRoute
    }
    '/_classimed/library': {
      id: '/_classimed/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof ClassimedLibraryRouteImport
      parentRoute: typeof ClassimedRoute
    }
    '/_classimed/glossary': {
      id: '/_classimed/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof ClassimedGlossaryRouteImport
      parentRoute: typeof ClassimedRoute
    }
  }
}

interface ClassimedRouteChildren {
  ClassimedGlossaryRoute: typeof ClassimedGlossaryRoute
  ClassimedLibraryRoute: typeof ClassimedLibraryRoute
  ClassimedReaderRoute: typeof ClassimedReaderRoute
  ClassimedTodoRoute: typeof ClassimedTodoRoute
}

const ClassimedRouteChildren: ClassimedRouteChildren = {
  ClassimedGlossaryRoute: ClassimedGlossaryRoute,
  ClassimedLibraryRoute: ClassimedLibraryRoute,
  ClassimedReaderRoute: ClassimedReaderRoute,
  ClassimedTodoRoute: ClassimedTodoRoute,
}

const ClassimedRouteWithChildren = ClassimedRoute._addFileChildren(
  ClassimedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClassimedRoute: ClassimedRouteWithChildren,
  DesignRoute: DesignRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
